# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Uu-53vJrgrogw0VUY9ZS0c8W87EA2aZ
"""

import random
import json
import os
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# File paths in Google Drive
AES_SBOX_FILE = "/content/drive/MyDrive/aes_sbox.json"
DES_SBOX_FILE = "/content/drive/MyDrive/des_sbox.json"

# AES S-Box Generation
def generate_aes_sbox():
    sbox = list(range(256))  # Create a list with values from 0 to 255
    random.shuffle(sbox)  # Randomly shuffle the values to create a unique S-Box
    return sbox

# DES S-Box Generation
def generate_des_sbox():
    sbox = list(range(256))  # Create a list with values from 0 to 255
    random.shuffle(sbox)  # Randomly shuffle the values to create a unique S-Box
    return sbox

# Save S-Box to a file
def save_sbox(filename, sbox):
    with open(filename, "w") as file:
        json.dump(sbox, file)

# Load S-Box from a file (if exists), otherwise generate and save
def load_or_generate_sbox(filename, generate_func):
    if os.path.exists(filename):
        with open(filename, "r") as file:
            return json.load(file)
    else:
        sbox = generate_func()
        save_sbox(filename, sbox)
        return sbox

# Load or generate AES and DES S-Boxes
aes_sbox = load_or_generate_sbox(AES_SBOX_FILE, generate_aes_sbox)
des_sbox = load_or_generate_sbox(DES_SBOX_FILE, generate_des_sbox)

print("AES S-Box loaded/saved successfully.")
print("DES S-Box loaded/saved successfully.")
